import { DEFAULT_META_DESCRIPTION, DEFAULT_SEO_TITLE } from '~/constants/seo'

export const HOME_PAGE_TITLE = '홈'
export const HOME_PAGE_META_DESCRIPTION = DEFAULT_META_DESCRIPTION
export const HOME_PAGE_OG_TITLE = DEFAULT_SEO_TITLE
