// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026. 3. 5. AM 1:55:08
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/sejiwork/subProject/sejinjja.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sejiwork/subProject/sejinjja.github.io/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sejiwork/subProject/sejinjja.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sejiwork/subProject/sejinjja.github.io/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sejiwork/subProject/sejinjja.github.io/plugins/**/*.{js,ts,mjs}","C:/Users/sejiwork/subProject/sejinjja.github.io/composables/**/*.{js,ts,mjs}","C:/Users/sejiwork/subProject/sejinjja.github.io/utils/**/*.{js,ts,mjs}","C:/Users/sejiwork/subProject/sejinjja.github.io/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sejiwork/subProject/sejinjja.github.io/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sejiwork/subProject/sejinjja.github.io/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/sejiwork/subProject/sejinjja.github.io/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;